services:
  database:
    image: "neo4j"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
  scraper:
    build: scraper
    environment:
      - VOTE_SCRAPER_NEO4J_URI=neo4j://database:7687
      - VOTE_SCRAPER_NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - .:/workspace:cached
      - ./data:/data/bioguide
    restart: no
volumes:
  neo4j-data:
    